# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# ファイル末尾の改行を許可
TrailingBlankLines:
  EnforcedStyle: final_blank_line

LineLength:
  Max: 100

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - '.bundle/**/*'

